import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-lvh pb-10">
        <div className="h-full w-screen">
        {children}

        </div>
      </body>
      <footer className="w-screen text-center flex gap-1 h-10 place-items-center place-content-center text-gray-500 text-sm">
        Created very quickly by <a className="hover:underline" href="https://www.instagram.com/loganwhitten512">Logan Whitten</a>
      </footer>
    </html>
  );
}
